# Random Forest Regressor aplicada a base de preço casas

In [4]:
# Numérico
import pandas as pd
import numpy as np

# Gráficos
import matplotlib.pyplot as plt
import plotly.express as px 

# Algoritmos de Aprendizagem
from sklearn.model_selection import train_test_split
# Importação do Random Forest
from sklearn.ensemble import RandomForestRegressor

# Metricas 
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [5]:
db_casas = pd.read_csv('house_prices.csv')

# predictor values in matrix shape
X_casas = db_casas.iloc[:,3:19].values

# prices
y_casas = db_casas.iloc[:,2].values

## Divisao da base
X_casas_treinamento, X_casas_test, y_casas_treinamento, y_casas_test = train_test_split(X_casas, y_casas, test_size=0.3, random_state=0)
X_casas_treinamento.shape, X_casas_teste.shape

((15129, 16), (6484, 16))

In [6]:
### Instaciando o algoritmo
RDF_regressor = RandomForestRegressor()

# Treinar
RDF_regressor.fit(X_casas_treinamento, y_casas_treinamento)

# Avaliar na base de treino
score_rdf_train = RDF_regressor.score(X_casas_treinamento, y_casas_treinamento)
# Avaliar na base de teste
score_rdf_test = RDF_regressor.score(X_casas_test, y_casas_test)

In [7]:
print(f'TREINAMENTO: {score_rdf_train}')
print(f' TESTE: {score_rdf_test}')

TREINAMENTO: 0.9811485354693066
 TESTE: 0.878919879427021


1. Regressão Linear Simples: 0.48
2. Regressaõ Linear Múltipla: 0.68
3. Regressão Polinomial: 0.81
4. Regressão Árvore: 0.73
5. Regressão RDF: 0.88

In [8]:
y_pred = RDF_regressor.predict(X_casas_test)

In [9]:
y_pred 

array([ 309390.5       , 1704829.13333333,  529799.5       , ...,
        368349.14      ,  235285.93      ,  202724.6       ])

In [10]:
y_casas_test

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [11]:
y_pred - y_casas_test

array([ 12390.5       , 126829.13333333, -32300.5       , ...,
       -11650.86      , -32714.07      ,  -3275.4       ])

In [14]:
mean_absolute_error(y_casas_test, y_pred)

68002.7891765414

Em média o algoritmo vai errar $\pm 68K \$$