In [1]:
from PIL import Image
import numpy as np
import cv2 
import os

In [2]:
### Extraindo o yalefaces.zip
# import zipfile
# path: str = r'C:\Users\VictorCampos\Udemy\Data_Science\VisaoComputacional\yalefaces.zip'
# zip_obj = zipfile.ZipFile(file=path, mode='r')
# zip_obj.extractall('./')
# zip_obj.close()

### Criação do Classificador

In [3]:
pasta_treinamento = r'C:\Users\VictorCampos\Udemy\Data_Science\VisaoComputacional\yalefaces\train'

In [4]:
def dados_imagem():
  caminhos = [os.path.join(pasta_treinamento, f) for f in os.listdir(pasta_treinamento)]
  faces = []
  ids = []
  for caminho in caminhos:
    if caminho == '/content/yalefaces/treinamento/.ipynb_checkpoints':
      continue
    imagem = Image.open(caminho).convert('L')
    imagem_np = np.array(imagem, 'uint8')
    id = int(os.path.split(caminho)[1].split('.')[0].replace('subject', ''))
    ids.append(id)
    faces.append(imagem_np)
  return np.array(ids), faces

In [5]:
ids, faces = dados_imagem()

In [6]:
ids # [10 6 8 ... 8 8 8]

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14,
       14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15])

In [7]:
### Salvando um classificador

LBPH = cv2.face.LBPHFaceRecognizer_create()
LBPH.train(faces, ids)
LBPH.write('LPBH_Classifier.yml')

### Carregar o classificador

In [8]:
reconhecedor = cv2.face.LBPHFaceRecognizer_create()
reconhecedor.read('LPBH_Classifier.yml')

In [13]:
imagem_teste: str = r'yalefaces/test/subject14.sad.gif'




In [14]:
imagem = Image.open(imagem_teste).convert('L')
imagem_np = np.array(imagem, dtype='uint8')
print(imagem_np)

[[130 130 130 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 246 223]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [ 68  68  68 ...  68  68  68]]


In [15]:
id_previsto, _ = reconhecedor.predict(imagem_np)

In [16]:
id_previsto

14